# Generated by Django 5.2 on 2026-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_date',
            field=models.TimeField(auto_now=True),
        ),
    ]
